### ISSUE TITLE
Continued support for legacy versions (10.x)?

### ISSUE THREAD

**Issue by parties** [tomasbonco/gitlabtree#30]
My organization uses a self-hosted Gitlab that is currently using GitLab@10.x. We have plans to move forward to 11.x soon, but it's still a ways out.

I imagine now that GitLab 11.x has a similar feature this plugin could/would change considerably by building off of existing functionality from 11.x.

In the interest of supporting a larger audience, what would it take to support, say, GitLab's latest two major versions?

Thoughts?

**Comment by tomasbonco** [comment]
Hi! To make it clear: does plugin work for you now?

**Comment by parties** [comment]
Yes it does.

**Comment by tomasbonco** [comment]
In that case, I'll keep the support for legacy GitLab while changing the extension to cooperate with the new version.
Thank you very much for this issue, because I completely forgot about this use case (and I started this project because of it) and wanted to throw away most of the code. God bless you!

**Comment by parties** [comment]
Thank _you_ for continuing support! 🙏🙌
