### ISSUE TITLE
Addon is active on all URLs

### ISSUE THREAD

**Issue by nicexe** [tomasbonco/gitlabtree#7]
https://github.com/tomasbonco/gitlabtree/blob/0dfed312b8b7e6a17f56313d38de1fe33250d01e/manifest.json#L26

I know you can run a self-hosted instance of GitLab but having a GitLab specific add-on active on all pages seems scary

**Comment by tomasbonco** [comment]
Can you suggest a solution that would work with self-hosted instances?

**Comment by nicexe** [comment]
Very far from perfect but maybe something like this
```json
"matches": [
  "*://*git*"
]
```

**Comment by tomasbonco** [comment]
Well, to be honest, even I do have a problem with current situation. But in the other hand I created this extension primarly because company I work for is using self-hosted gitlab on intranet. Trying to guess every possible URL is not real in my opinion.

So the way it works is it searches for matching `<meta>` tag [1] on every website. Now this has impact on security as well as performance. I believe answer for a question "is this extension secure? does it collect or log anything?" can be answered by looking at the code. You can also build it yourself and check byte-to-byte. It does not (collect/log anything). It does check for meta tag as the very first thing, so I tried to at least minize performance impact as possible.

Now I know this is not perfect, I wish it could be better, but I have no idea how to it other way while making sure it runs correctly on every URL that runs GitLab.

(So, the problem I have with your solution is - it limits possible URLs.)

[1] https://github.com/tomasbonco/gitlabtree/blob/0dfed312b8b7e6a17f56313d38de1fe33250d01e/src/inject/inject.ts#L38
